[workspace]
authors = ["jadepurring <paling-loloda@pm.me>"]
channels = ["conda-forge", "bioconda"]
name = "fold_tree"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
foldseek = ">=10.941cd33,<11"
snakemake = ">=9.9.0,<10"
snakedeploy = ">=0.11.0,<0.12"
snakefmt = ">=0.11.0,<0.12"
iqtree = ">=3.0.1,<4"
muscle = ">=5.3,<6"
quicktree = ">=2.5,<3"
python-wget = ">=3.2,<4"
ete3 = ">=3.1.3,<4"
statsmodels = ">=0.14.5,<0.15"
toytree = ">=3.0.10,<4"
toyplot = ">=2.0.0,<3"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.4,<3"
biopython = ">=1.85,<2"
python = ">=3.12.11,<3.13"
fasttree = ">=2.1.11,<3"
clustalo = ">=1.2.4,<2"
